//
//  Constant.m
//  Hit_API_NSURLSession
//
//  Created by SILICON on 28/07/16.
//  Copyright © 2016 Apple. All rights reserved.
//

#import "Constant.h"

@implementation Constant

NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_SUNDAY = @"Sun";
NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_MONDAY = @"Mon";
NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_TUESDAY = @"Tues";
NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_WEDNESDAY = @"Wed";
NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_THURSDAY = @"Thu";
NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_FRIDAY = @"Fri";
NSString *const FT_UPCOMING_CLASSES_SESSION_SORT_WEEKNAME_SATURDAY = @"Sat";

@end
